name: Issue Auto Labeling

on:
    issues:
        types: [opened, edited]

permissions:
    issues: write

jobs:
    label:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7
              
            - name: Apply Labels
              uses: ./.github/actions/apply-label
              with:
                mode: issue
                github-token: ${{secrets.GITHUB_TOKEN}}