name: Sync Labels

on:
  workflow_dispatch:
    inputs:
      prune:
        description: Delete unmanaged labels
        type: boolean
        default: false

      dry-run:
        description: Preview changes without modifying labels
        type: boolean
        default: false

permissions:
    issues: write

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7

            - name: Sync Labels
              uses: ./.github/actions/sync-labels
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                prune: ${{ inputs.prune }}
                dry-run: ${{ inputs.dry-run }}